---
- name: Installer et configurer Apache
  hosts: all
  become: yes

  tasks:
    - name: Mettre à jour le cache APT
      apt:
        update_cache: yes

    - name: Installer Apache
      apt:
        name: apache2
        state: present

    - name: Vérifier si systemd est disponible
      stat:
        path: /bin/systemctl
      register: systemd_check

    - name: Démarrer et activer Apache (systemd)
      service:
        name: apache2
        state: started
        enabled: yes
      when: systemd_check.stat.exists

    - name: Démarrer Apache sans systemd
      command: apachectl start
      when: not systemd_check.stat.exists
