---
- name: Test du bon fonctionnement d'Ansible
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Mettre à jour le cache APT
      apt:
        update_cache: yes

    - name: Installer cmatrix
      apt:
        name: cmatrix
        state: present

    - name: Vérifier que cmatrix est installé
      command: dpkg -l cmatrix
      register: cmatrix_check
      failed_when: cmatrix_check.rc != 0
      changed_when: false

    - name: Afficher le résultat du test
      debug:
        msg: "cmatrix est bien installé ✔️"
