---
- name: Test du bon fonctionnement d'Ansible
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Mettre à jour le cache APT (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Installer cmatrix
      package:
        name: cmatrix
        state: present

    - name: Vérifier que cmatrix est installé
      command: cmatrix -h
      register: cmatrix_check
      changed_when: false

    - name: Afficher le résultat du test
      debug:
        msg: "cmatrix est bien installé et fonctionnel ✔️"
